#
# Autogenerated by Thrift Compiler (0.9.1)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py:new_style,utf8strings,slots
#

MAX_HEALTH = 100
TANK_SPEED = 0.1
TANK_ROTATION = 0.005
TANK_ROTATION_TOLERANCE = 0.05
BULLET_SPEED = 0.2
TANK_RADIUS = 15
