#
# Autogenerated by Thrift Compiler (0.9.1)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py:new_style,utf8strings,slots
#

MAX_HEALTH = 100
TANK_SPEED = 0.1
BULLET_SPEED = 0.2
