version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/server/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/viewer/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/sample-groovy/"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/rusty-hunter/"
    schedule:
      interval: "daily"
