---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: rusty-hunter
  name: rusty-hunter-1
  namespace: codetanks
spec:
  template:
    metadata:
      labels:
        app: rusty-hunter
      name: rusty-hunter-1
      namespace: codetanks
    spec:
      restartPolicy: Never
      containers:
        - image: ghcr.io/mortenlj/codetanks/rusty-hunter:latest
          imagePullPolicy: Always
          name: rusty-hunter
          env:
            - name: SERVER_URI
              value: tcp://codetanks-server-demo:13337
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: rusty-hunter
  name: rusty-hunter-2
  namespace: codetanks
spec:
  template:
    metadata:
      labels:
        app: rusty-hunter
      name: rusty-hunter-2
      namespace: codetanks
    spec:
      restartPolicy: Never
      containers:
        - image: ghcr.io/mortenlj/codetanks/rusty-hunter:latest
          imagePullPolicy: Always
          name: rusty-hunter
          env:
            - name: SERVER_URI
              value: tcp://codetanks-server-demo:13337
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: groovy-randomizer
  name: groovy-randomizer-3
  namespace: codetanks
spec:
  template:
    metadata:
      labels:
        app: groovy-randomizer
      name: groovy-randomizer-3
      namespace: codetanks
    spec:
      restartPolicy: Never
      containers:
        - image: ghcr.io/mortenlj/codetanks/groovy-randomizer:latest
          imagePullPolicy: Always
          name: groovy-randomizer
          env:
            - name: SERVER_URI
              value: tcp://codetanks-server-demo:13337
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: groovy-randomizer
  name: groovy-randomizer-4
  namespace: codetanks
spec:
  template:
    metadata:
      labels:
        app: groovy-randomizer
      name: groovy-randomizer-4
      namespace: codetanks
    spec:
      restartPolicy: Never
      containers:
        - image: ghcr.io/mortenlj/codetanks/groovy-randomizer:latest
          imagePullPolicy: Always
          name: groovy-randomizer
          env:
            - name: SERVER_URI
              value: tcp://codetanks-server-demo:13337
