VERSION 0.7

FROM alpine:3
WORKDIR /code

protoc:
    RUN wget https://github.com/protocolbuffers/protobuf/releases/download/v26.1/protoc-26.1-linux-x86_64.zip
    RUN unzip protoc-26.1-linux-x86_64.zip -d /usr/local/

src:
    COPY protobuf ./
    SAVE ARTIFACT ./ /src

python:
    FROM +protoc
    COPY +src/src ./
    RUN mkdir -p gen/python/ibidem/codetanks/domain && touch gen/python/ibidem/codetanks/domain/__init__.py
    RUN protoc messages.proto \
        --python_out gen/python/ibidem/codetanks/domain
    SAVE ARTIFACT gen/python /python

java:
    FROM +protoc
    COPY +src/src ./
    RUN mkdir -p gen/java
    RUN protoc messages.proto \
        --java_out gen/java
    SAVE ARTIFACT gen/java /java

all:
    BUILD +python
    BUILD +java
