FROM namely/protoc:latest
WORKDIR /code
COPY protobuf ./

python:
    RUN mkdir -p gen/python/ibidem/codetanks/domain && touch gen/python/ibidem/codetanks/domain/__init__.py
    RUN protoc messages.proto \
        --python_out gen/python/ibidem/codetanks/domain
    SAVE ARTIFACT gen/python /python
