VERSION 0.8

FROM busybox

uv:
    FROM ghcr.io/astral-sh/uv:latest

    SAVE ARTIFACT /uv

deps:
    FROM python:3.13

    WORKDIR /app
    COPY +uv/uv /bin/uv

    COPY pyproject.toml uv.lock .
    RUN uv sync --no-install-workspace --locked --compile-bytecode

    SAVE ARTIFACT .venv
    SAVE IMAGE --cache-hint


build:
    FROM +deps

    COPY --dir ibidem .
    COPY ../domain+python/* ./
    RUN uv sync --locked --compile-bytecode --no-editable

    SAVE ARTIFACT .venv
    SAVE IMAGE --cache-hint


protobuf:
    COPY ../domain+python/* ./
    SAVE ARTIFACT ./ibidem/codetanks/domain AS LOCAL ./ibidem/codetanks/domain


test:
    FROM +build
    RUN uv sync --locked --compile-bytecode --group=dev
    COPY tests tests
    ENV PYTHONPATH=.
    RUN uv run pytest


docker:
    FROM python:3.13-slim

    WORKDIR /app

    ARG NATIVEPLATFORM
    COPY --dir +build/.venv .

    ENV PATH="/bin:/usr/bin:/usr/local/bin:/app/.venv/bin"

    ENTRYPOINT ["codetanks"]

    ARG EARTHLY_GIT_SHORT_HASH
    ARG IMAGE_TAG=$EARTHLY_GIT_SHORT_HASH
    ARG EARTHLY_GIT_PROJECT_NAME
    ARG BASEIMAGE=ghcr.io/$EARTHLY_GIT_PROJECT_NAME

    SAVE IMAGE --push ${BASEIMAGE}/server:${IMAGE_TAG} ${BASEIMAGE}/server:latest

launch:
    LOCALLY
    ARG EARTHLY_GIT_PROJECT_NAME
    ARG BASEIMAGE=ghcr.io/$EARTHLY_GIT_PROJECT_NAME
    RUN docker run --label codetanks=server --net=host --rm ${BASEIMAGE}/server:latest
