VERSION 0.8

FROM busybox

uv:
    FROM ghcr.io/astral-sh/uv:latest

    SAVE ARTIFACT /uv

deps:
    FROM python:3.13

    WORKDIR /app
    COPY +uv/uv /bin/uv

    COPY pyproject.toml uv.lock .
    RUN uv sync --no-install-workspace --locked --compile-bytecode --no-dev

    SAVE ARTIFACT .venv
    SAVE IMAGE --cache-hint


build:
    FROM +deps

    COPY --dir ibidem .
    COPY +protobuf/domain ./ibidem/codetanks/domain
    RUN uv sync --locked --compile-bytecode --no-editable --no-dev

    SAVE ARTIFACT .venv
    SAVE IMAGE --cache-hint


protobuf:
    FROM +deps
    ENV PROTOBUF_SRC=profobuf/
    COPY ../domain+src/src/* $PROTOBUF_SRC
    RUN uv sync --no-install-workspace --locked --compile-bytecode --dev
    RUN mkdir -p ./ibidem/codetanks/domain
    RUN .venv/bin/python -m grpc_tools.protoc -I$PROTOBUF_SRC --python_out=./ibidem/codetanks/domain --pyi_out=./ibidem/codetanks/domain --grpc_python_out=./ibidem/codetanks/domain $PROTOBUF_SRC/messages.proto
    SAVE ARTIFACT ibidem/codetanks/domain domain AS LOCAL ibidem/codetanks/domain


test:
    FROM +build
    RUN uv sync --locked --compile-bytecode --dev
    COPY tests tests
    ENV PYTHONPATH=.
    RUN uv run pytest


docker:
    FROM python:3.13-slim

    WORKDIR /app

    ARG NATIVEPLATFORM
    COPY --dir +build/.venv .

    ENV PATH="/bin:/usr/bin:/usr/local/bin:/app/.venv/bin"

    ENTRYPOINT ["codetanks"]

    ARG EARTHLY_GIT_SHORT_HASH
    ARG IMAGE_TAG=$EARTHLY_GIT_SHORT_HASH
    ARG EARTHLY_GIT_PROJECT_NAME
    ARG BASEIMAGE=ghcr.io/$EARTHLY_GIT_PROJECT_NAME

    SAVE IMAGE --push ${BASEIMAGE}/server:${IMAGE_TAG} ${BASEIMAGE}/server:latest

launch:
    LOCALLY
    ARG EARTHLY_GIT_PROJECT_NAME
    ARG BASEIMAGE=ghcr.io/$EARTHLY_GIT_PROJECT_NAME
    RUN docker run --label codetanks=server --net=host --rm ${BASEIMAGE}/server:latest
