VERSION 0.8

FROM busybox

uv:
    FROM ghcr.io/astral-sh/uv:latest

    SAVE ARTIFACT /uv

deps:
    FROM python:3.13

    WORKDIR /app
    COPY +uv/uv /bin/uv

    COPY pyproject.toml uv.lock .
    RUN uv sync --no-install-workspace --locked --compile-bytecode

    SAVE ARTIFACT .venv
    SAVE IMAGE --cache-hint


build:
    FROM +deps

    RUN uv sync --locked --compile-bytecode

    COPY --dir ibidem .
    COPY ../domain+python/* ./

    SAVE ARTIFACT ibidem
    SAVE IMAGE --cache-hint


protobuf:
    COPY ../domain+python/* ./
    SAVE ARTIFACT ./ibidem/codetanks/domain AS LOCAL ./ibidem/codetanks/domain


docker:
    FROM python:3.13-slim

    WORKDIR /app

    ARG NATIVEPLATFORM
    COPY --dir +deps/.venv .
    COPY --platform=${NATIVEPLATFORM} --dir +build/ibidem .

    ENV PATH="/bin:/usr/bin:/usr/local/bin:/app/.venv/bin"

    ENTRYPOINT ["codetanks-viewer"]

    ARG EARTHLY_GIT_SHORT_HASH
    ARG IMAGE_TAG=$EARTHLY_GIT_SHORT_HASH
    ARG EARTHLY_GIT_PROJECT_NAME
    ARG BASEIMAGE=ghcr.io/$EARTHLY_GIT_PROJECT_NAME

    SAVE IMAGE --push ${BASEIMAGE}/viewer:${IMAGE_TAG} ${BASEIMAGE}/viewer:latest
