VERSION 0.7

#FROM openjdk:15-jdk-alpine
FROM eclipse-temurin:21-alpine
WORKDIR /groovy-randomizer

deps:
    ENV GRADLE_OPTS="-Dorg.gradle.daemon=false"
    COPY build.gradle ./
    COPY gradlew gradlew
    COPY gradle gradle
    RUN ./gradlew assemble

test:
    FROM +deps
    COPY ../domain+java/java/* build/generated/source/proto/main/java
    COPY src src
    RUN ./gradlew test

build:
    FROM +test
    RUN ./gradlew shadowJar
    SAVE ARTIFACT build/libs/groovy-randomizer-0.1-SNAPSHOT-all.jar /jar

protobuf:
    COPY ../domain+java/java/* build/generated/source/proto/main/java
    SAVE ARTIFACT build/generated/source/proto/main/java AS LOCAL build/generated/source/proto/main/java/ibidem

docker:
    COPY --platform=linux/amd64 +build/jar ./groovy-randomizer.jar
    ENTRYPOINT ["java", "-jar", "groovy-randomizer.jar"]

    ARG EARTHLY_GIT_SHORT_HASH
    ARG IMAGE_TAG=$EARTHLY_GIT_SHORT_HASH
    ARG EARTHLY_GIT_PROJECT_NAME
    ARG BASEIMAGE=ghcr.io/$EARTHLY_GIT_PROJECT_NAME

    SAVE IMAGE --push ${BASEIMAGE}/groovy-randomizer:${IMAGE_TAG} ${BASEIMAGE}/groovy-randomizer:latest
