domain:
    FROM namely/protoc:latest
    WORKDIR /code
    COPY domain domain
    RUN mkdir -p gen/python/ibidem/codetanks/domain && touch gen/python/ibidem/codetanks/domain/__init__.py
    RUN protoc domain/protobuf/messages.proto --proto_path domain/protobuf \
        --python_out gen/python/ibidem/codetanks/domain
    SAVE ARTIFACT gen/python /python AS LOCAL build/python

server:
    FROM python:3
    WORKDIR /code
    RUN pip install --upgrade wheel pip setuptools
    COPY server/requirements.txt ./
    RUN pip wheel -r requirements.txt --wheel-dir=wheels
    COPY server server
    SAVE ARTIFACT server /src
    SAVE ARTIFACT wheels /wheels
