FROM openjdk:15-jdk-alpine
WORKDIR /sample-groovy

deps:
    ENV GRADLE_OPTS="-Dorg.gradle.daemon=false"
    COPY build.gradle ./
    COPY gradlew gradlew
    COPY gradle gradle
    RUN ./gradlew assemble

test:
    FROM +deps
    COPY ../domain+java/java/* build/generated/source/proto/main/java
    COPY src src
    RUN ./gradlew test

build:
    FROM +test
    RUN ./gradlew shadowJar
    SAVE ARTIFACT build/libs/sample-groovy-0.1-SNAPSHOT-all.jar /jar

docker:
    COPY +build/jar ./sample-groovy.jar
    ENTRYPOINT ["java", "-jar", "sample-groovy.jar"]
    SAVE IMAGE mortenlj/codetanks-sample-groovy:latest
