VERSION 0.8

IMPORT github.com/mortenlj/earthly-lib/rust/commands AS lib-commands
IMPORT github.com/mortenlj/earthly-lib/rust/targets AS lib-targets

FROM rust:1

WORKDIR /code

chef-planner:
    FROM lib-targets+common-build-setup

    DO lib-commands+CHEF_PREPARE
    SAVE ARTIFACT recipe.json

build-target:
    FROM lib-targets+prepare-tier1

    RUN apt-get --yes update && apt-get --yes install protobuf-compiler
    COPY +chef-planner/recipe.json recipe.json
    ENV PROTOBUF_SRC=src/protobuf/
    COPY --dir build.rs .
    COPY ../domain+src/src/* $PROTOBUF_SRC

    ARG target
    DO lib-commands+BUILD --target ${target}

    ARG version=unknown
    SAVE ARTIFACT --if-exists target/${target}/release/rusty-hunter rusty-hunter

docker:
    FROM cgr.dev/chainguard/static:latest

    WORKDIR /bin
    ARG target=x86_64-unknown-linux-musl
    ARG NATIVEPLATFORM
    COPY --platform=${NATIVEPLATFORM} (+build-target/rusty-hunter --target=$target) rusty-hunter

    ENTRYPOINT ["/bin/rusty-hunter"]

    # builtins must be declared
    ARG EARTHLY_GIT_SHORT_HASH
    ARG IMAGE_TAG=$EARTHLY_GIT_SHORT_HASH
    ARG EARTHLY_GIT_PROJECT_NAME
    ARG BASEIMAGE=ghcr.io/$EARTHLY_GIT_PROJECT_NAME

    SAVE IMAGE --push ${BASEIMAGE}/rusty-hunter:${IMAGE_TAG} ${BASEIMAGE}/rusty-hunter:latest
