VERSION 0.7

FROM busybox

prepare:
    FROM rust:1
    WORKDIR /rusty-hunter
    RUN cargo install cargo-chef
    RUN apt-get --yes update && apt-get --yes install cmake musl-tools protobuf-compiler
    RUN rustup target add x86_64-unknown-linux-musl

chef-planner:
    FROM +prepare
    COPY --dir src Cargo.lock Cargo.toml build.rs .
    COPY ../domain+src/src/* target/proto/
    RUN cargo chef prepare --recipe-path recipe.json
    SAVE ARTIFACT recipe.json

chef-cook:
    FROM +prepare
    COPY +chef-planner/recipe.json recipe.json
    RUN cargo chef cook --recipe-path recipe.json --release --target x86_64-unknown-linux-musl

build:
    FROM +chef-cook

    ENV PROTOBUF_SRC=src/protobuf/
    COPY --dir src Cargo.lock Cargo.toml build.rs .
    COPY ../domain+src/src/* $PROTOBUF_SRC
    # builtins must be declared
    ARG EARTHLY_GIT_SHORT_HASH
    ARG VERSION=$EARTHLY_GIT_SHORT_HASH
    RUN cargo build --release --target x86_64-unknown-linux-musl

    SAVE ARTIFACT target/x86_64-unknown-linux-musl/release/rusty-hunter rusty-hunter

docker:
    FROM cgr.dev/chainguard/static:latest

    WORKDIR /bin
    COPY +build/rusty-hunter rusty-hunter

    ENTRYPOINT ["/bin/rusty-hunter"]

    # builtins must be declared
    ARG EARTHLY_GIT_SHORT_HASH

    ARG EARTHLY_GIT_SHORT_HASH
    ARG IMAGE_TAG=$EARTHLY_GIT_SHORT_HASH
    ARG EARTHLY_GIT_PROJECT_NAME
    ARG BASEIMAGE=ghcr.io/$EARTHLY_GIT_PROJECT_NAME

    SAVE IMAGE --push ${BASEIMAGE}/rusty-hunter:${IMAGE_TAG} ${BASEIMAGE}/rusty-hunter:latest
