name: Build and test

on:
  push:

env:
  BASEIMAGE: ghcr.io/${{ github.repository }}
  cache_image: ghcr.io/${{ github.repository }}/cache:cache

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: "Set image version"
      id: set-image-tag
      run: |
        export IMAGE_TAG="$(date +%Y%m%d%H%M%S)-$(git describe --always --dirty --exclude '*')"
        echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
        echo "image=${BASEIMAGE}:${IMAGE_TAG}" >> ${GITHUB_OUTPUT}
    - uses: earthly/actions-setup@v1
      with:
        version: "latest" # or pin to an specific version, e.g. "v0.6.10"
    - name: Login to GitHub Packages Docker Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and possibly push
      env:
        EARTHLY_PUSH: "${{ github.ref == 'refs/heads/master' }}"
        EARTHLY_ORG: ${{ secrets.EARTHLY_ORG }}
        EARTHLY_SATELLITE: ${{ secrets.EARTHLY_SATELLITE }}
        EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      run: |
        earthly --ci --remote-cache=${cache_image} +all --IMAGE_TAG="${IMAGE_TAG}" --BASEIMAGE="${BASEIMAGE}"
    outputs:
      image: "${{ steps.set-image-tag.outputs.image }}"
