name: build and test

on:
  - push
  - pull_request

env:
  BAZELISK_VERSION: v1.1.0
  BAZELISK_PATH: "/home/runner/bazelisk"
  BAZEL: "/home/runner/bazelisk/bazel"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Mount bazel cache
        uses: actions/cache@v2
        with:
          path: "/home/runner/.cache/bazel"
          key: bazel-${{ github.sha }}
          restore-keys: |
            bazel-

      - name: Get Bazelisk
        id: get-bazelisk
        uses: actions/cache@v2
        with:
          path: "${{ env.BAZELISK_PATH }}"
          key: bazelisk-${{ env.BAZELISK_VERSION }}

      - name: Install bazelisk
        if: steps.get-bazelisk.outputs.cache-hit != 'true'
        run: |
          curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/${BAZELISK_VERSION}/bazelisk-linux-amd64"
          mkdir -p "${BAZELISK_PATH}"
          mv bazelisk-linux-amd64 "${BAZEL}"
          chmod +x "${BAZEL}"

      - name: Build
        run: |
          "${BAZEL}" build //...

      - name: Test
        run: |
          "${BAZEL}" test --test_output all //...
